/*
   Generated by EX4-TO-MQ4 decompiler V4.0.438.4 [-]
   Website: https://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright 2013, MetaQuotes Software Corp."
#property link      "vahid_nassiri@yahoo.com"

extern double Lot = 0.01;
extern int StopLoss = 20;
extern int TakeProfit = 10;
extern int Gap = 5;
extern int Pip = 20;
extern bool Buy_Stop = TRUE;
extern bool Sell_Stop = TRUE;
extern bool Buy_Limit = FALSE;
extern bool Sell_Limit = FALSE;
extern bool Remove_Pending = TRUE;
extern bool Trail = FALSE;
extern int Trailing_Stop = 3;
extern bool comment = FALSE;
int gi_132;
int gi_136;
int gi_140;
int gi_144;
int gi_148;
int gi_152;
int gi_156;
int gi_160;
double g_order_open_price_164;
double g_order_open_price_172;
double g_order_open_price_180;
double g_order_open_price_188;
double g_price_196;
double g_price_204;
double g_price_212;
double g_price_220;
double g_price_228;
double g_price_236;
double g_price_244;
double g_price_252;
double g_price_260;
double g_price_268;
double g_price_276;
double g_price_284;

int init() {
   if (!(Digits == 2) && !(Digits == 4)) {
      if (Digits == 3 || Digits == 5) {
         Pip = 10 * Pip;
         Gap = 10 * Gap;
         StopLoss = 10 * StopLoss;
         TakeProfit = 10 * TakeProfit;
         Trailing_Stop = 10 * Trailing_Stop;
      }
   }
   if (Gap < MarketInfo(Symbol(), MODE_STOPLEVEL)) Gap = MarketInfo(Symbol(), MODE_STOPLEVEL);
   if (Trailing_Stop < MarketInfo(Symbol(), MODE_STOPLEVEL)) Trailing_Stop = MarketInfo(Symbol(), MODE_STOPLEVEL);
   return (0);
}

int start() {
   g_order_open_price_164 = 0;
   if (Buy_Stop == TRUE) {
      gi_132 = f0_2(Symbol(), 12345);
      if (gi_132 < 1) {
         g_price_196 = NormalizeDouble(Ask + Gap * Point, Digits - 1);
         g_price_228 = 0;
         g_price_236 = 0;
         f0_5();
      }
      if (gi_132 > 0) {
         for (int pos_0 = OrdersTotal() - 1; pos_0 >= 0; pos_0--) {
            if (OrderSelect(pos_0, SELECT_BY_POS, MODE_TRADES) == TRUE) {
               if (OrderSymbol() == Symbol()) {
                  if (OrderMagicNumber() == 12345) {
                     g_order_open_price_164 = OrderOpenPrice();
                     if (NormalizeDouble(g_order_open_price_164 - Gap * Point, Digits - 1) > NormalizeDouble(Ask, Digits - 1)) {
                        gi_148 = f0_0(Symbol(), 12345, NormalizeDouble(g_order_open_price_164 - Gap * Point, Digits - 1));
                        if (gi_148 < 1) {
                           g_price_196 = NormalizeDouble(g_order_open_price_164 - Gap * Point, Digits - 1);
                           g_price_228 = 0;
                           g_price_236 = 0;
                           f0_5();
                        }
                     }
                     if (NormalizeDouble(g_order_open_price_164 + Gap * Point, Digits - 1) < NormalizeDouble(Ask + Pip * Point, Digits - 1)) {
                        gi_148 = f0_0(Symbol(), 12345, NormalizeDouble(g_order_open_price_164 + Gap * Point, Digits - 1));
                        if (gi_148 < 1) {
                           g_price_196 = NormalizeDouble(g_order_open_price_164 + Gap * Point, Digits - 1);
                           g_price_228 = 0;
                           g_price_236 = 0;
                           f0_5();
                        }
                     }
                  }
               }
            }
         }
      }
   }
   g_order_open_price_172 = 0;
   if (Sell_Stop == TRUE) {
      gi_136 = f0_2(Symbol(), 54321);
      if (gi_136 < 1) {
         g_price_204 = NormalizeDouble(Bid - Gap * Point, Digits - 1);
         g_price_244 = 0;
         g_price_252 = 0;
         f0_6();
      }
      if (gi_136 > 0) {
         for (int pos_4 = OrdersTotal() - 1; pos_4 >= 0; pos_4--) {
            if (OrderSelect(pos_4, SELECT_BY_POS, MODE_TRADES) == TRUE) {
               if (OrderSymbol() == Symbol()) {
                  if (OrderMagicNumber() == 54321) {
                     g_order_open_price_172 = OrderOpenPrice();
                     if (NormalizeDouble(g_order_open_price_172 + Gap * Point, Digits - 1) < NormalizeDouble(Bid, Digits - 1)) {
                        gi_152 = f0_0(Symbol(), 54321, NormalizeDouble(g_order_open_price_172 + Gap * Point, Digits - 1));
                        if (gi_152 < 1) {
                           g_price_204 = NormalizeDouble(g_order_open_price_172 + Gap * Point, Digits - 1);
                           g_price_244 = 0;
                           g_price_252 = 0;
                           f0_6();
                        }
                     }
                     if (NormalizeDouble(g_order_open_price_172 - Gap * Point, Digits - 1) > NormalizeDouble(Bid - Pip * Point, Digits - 1)) {
                        gi_152 = f0_0(Symbol(), 54321, NormalizeDouble(g_order_open_price_172 - Gap * Point, Digits - 1));
                        if (gi_152 < 1) {
                           g_price_204 = NormalizeDouble(g_order_open_price_172 - Gap * Point, Digits - 1);
                           g_price_244 = 0;
                           g_price_252 = 0;
                           f0_6();
                        }
                     }
                  }
               }
            }
         }
      }
   }
   g_order_open_price_180 = 0;
   if (Buy_Limit == TRUE) {
      gi_140 = f0_2(Symbol(), 6789);
      if (gi_140 < 1) {
         g_price_212 = NormalizeDouble(Ask - Gap * Point, Digits - 1);
         g_price_260 = 0;
         g_price_268 = 0;
         f0_3();
      }
      if (gi_140 > 0) {
         for (int pos_8 = OrdersTotal() - 1; pos_8 >= 0; pos_8--) {
            if (OrderSelect(pos_8, SELECT_BY_POS, MODE_TRADES) == TRUE) {
               if (OrderSymbol() == Symbol()) {
                  if (OrderMagicNumber() == 6789) {
                     g_order_open_price_180 = OrderOpenPrice();
                     if (NormalizeDouble(g_order_open_price_180 + Gap * Point, Digits - 1) < NormalizeDouble(Ask, Digits - 1)) {
                        gi_156 = f0_0(Symbol(), 6789, NormalizeDouble(g_order_open_price_180 + Gap * Point, Digits - 1));
                        if (gi_156 < 1) {
                           g_price_212 = NormalizeDouble(g_order_open_price_180 + Gap * Point, Digits - 1);
                           g_price_260 = 0;
                           g_price_268 = 0;
                           f0_3();
                        }
                     }
                     if (NormalizeDouble(g_order_open_price_180 - Gap * Point, Digits - 1) > NormalizeDouble(Ask - Pip * Point, Digits - 1)) {
                        gi_156 = f0_0(Symbol(), 6789, NormalizeDouble(g_order_open_price_180 - Gap * Point, Digits - 1));
                        if (gi_156 < 1) {
                           g_price_212 = NormalizeDouble(g_order_open_price_180 - Gap * Point, Digits - 1);
                           g_price_260 = 0;
                           g_price_268 = 0;
                           f0_3();
                        }
                     }
                  }
               }
            }
         }
      }
   }
   g_order_open_price_188 = 0;
   if (Sell_Limit == TRUE) {
      gi_144 = f0_2(Symbol(), 9876);
      if (gi_144 < 1) {
         g_price_220 = NormalizeDouble(Bid + Gap * Point, Digits - 1);
         g_price_276 = 0;
         g_price_284 = 0;
         f0_4();
      }
      if (gi_144 > 0) {
         for (int pos_12 = OrdersTotal() - 1; pos_12 >= 0; pos_12--) {
            if (OrderSelect(pos_12, SELECT_BY_POS, MODE_TRADES) == TRUE) {
               if (OrderSymbol() == Symbol()) {
                  if (OrderMagicNumber() == 9876) {
                     g_order_open_price_188 = OrderOpenPrice();
                     if (NormalizeDouble(g_order_open_price_188 - Gap * Point, Digits - 1) > NormalizeDouble(Bid, Digits - 1)) {
                        gi_160 = f0_0(Symbol(), 9876, NormalizeDouble(g_order_open_price_188 - Gap * Point, Digits - 1));
                        if (gi_160 < 1) {
                           g_price_220 = NormalizeDouble(g_order_open_price_188 - Gap * Point, Digits - 1);
                           g_price_276 = 0;
                           g_price_284 = 0;
                           f0_4();
                        }
                     }
                     if (NormalizeDouble(g_order_open_price_188 + Gap * Point, Digits - 1) < NormalizeDouble(Bid + Pip * Point, Digits - 1)) {
                        gi_160 = f0_0(Symbol(), 9876, NormalizeDouble(g_order_open_price_188 + Gap * Point, Digits - 1));
                        if (gi_160 < 1) {
                           g_price_220 = NormalizeDouble(g_order_open_price_188 + Gap * Point, Digits - 1);
                           g_price_276 = 0;
                           g_price_284 = 0;
                           f0_4();
                        }
                     }
                  }
               }
            }
         }
      }
   }
   if (Remove_Pending == TRUE) {
      for (int pos_16 = OrdersTotal() - 1; pos_16 >= 0; pos_16--) {
         OrderSelect(pos_16, SELECT_BY_POS, MODE_TRADES);
         if (OrderSymbol() == Symbol()) {
            if (OrderMagicNumber() == 12345 || OrderMagicNumber() == 54321 || OrderMagicNumber() == 6789 || OrderMagicNumber() == 9876) {
               if (OrderType() != OP_BUY && OrderType() != OP_SELL)
                  if (OrderOpenPrice() > NormalizeDouble(Ask + Pip * 2 * Point, Digits - 1) || NormalizeDouble(OrderOpenPrice() < Bid - Pip * 2 * Point, Digits - 1)) OrderDelete(OrderTicket());
            }
         }
      }
   }
   if (StopLoss != 0 || TakeProfit != 0) {
      for (int pos_20 = OrdersTotal() - 1; pos_20 >= 0; pos_20--) {
         if (OrderSelect(pos_20, SELECT_BY_POS, MODE_TRADES) == TRUE) {
            if (OrderSymbol() == Symbol()) {
               if ((StopLoss != 0 && OrderStopLoss() == 0.0) || (TakeProfit != 0 && OrderTakeProfit() == 0.0)) {
                  if (OrderMagicNumber() == 12345 || OrderMagicNumber() == 6789) {
                     OrderModify(OrderTicket(), OrderOpenPrice(), NormalizeDouble(OrderOpenPrice() - StopLoss * Point, Digits - 1), NormalizeDouble(OrderOpenPrice() + TakeProfit * Point,
                        Digits - 1), 0, Green);
                  }
                  if (OrderMagicNumber() == 54321 || OrderMagicNumber() == 9876) {
                     OrderModify(OrderTicket(), OrderOpenPrice(), NormalizeDouble(OrderOpenPrice() + StopLoss * Point, Digits - 1), NormalizeDouble(OrderOpenPrice() - TakeProfit * Point,
                        Digits - 1), 0, Green);
                  }
               }
            }
         }
      }
   }
   if (Trail == TRUE) {
      if (Trailing_Stop > 0) {
         for (int pos_24 = OrdersTotal() - 1; pos_24 >= 0; pos_24--) {
            if (OrderSelect(pos_24, SELECT_BY_POS, MODE_TRADES) == TRUE) {
               if (OrderSymbol() == Symbol()) {
                  if (OrderType() == OP_BUY) {
                     if (OrderMagicNumber() == 12345 || OrderMagicNumber() == 6789) {
                        if (Bid - OrderOpenPrice() > Trailing_Stop * Point)
                           if (OrderStopLoss() < Bid - Trailing_Stop * Point) OrderModify(OrderTicket(), OrderOpenPrice(), Bid - Trailing_Stop * Point, OrderTakeProfit(), 0, Green);
                     }
                  }
                  if (OrderType() == OP_SELL) {
                     if (OrderMagicNumber() == 54321 || OrderMagicNumber() == 9876) {
                        if (OrderOpenPrice() - Ask > Trailing_Stop * Point)
                           if (OrderStopLoss() > Ask + Trailing_Stop * Point) OrderModify(OrderTicket(), OrderOpenPrice(), Ask + Trailing_Stop * Point, OrderTakeProfit(), 0, Green);
                     }
                  }
               }
            }
         }
      }
   }
   if (comment == TRUE) f0_1();
   return (0);
}

void f0_5() {
   OrderSend(Symbol(), OP_BUYSTOP, Lot, g_price_196, 3, g_price_228, g_price_236, "My Buy Stop Position", 12345, 0, Blue);
}

void f0_6() {
   OrderSend(Symbol(), OP_SELLSTOP, Lot, g_price_204, 3, g_price_244, g_price_252, "My Sell Stop Position", 54321, 0, Red);
}

void f0_3() {
   OrderSend(Symbol(), OP_BUYLIMIT, Lot, g_price_212, 3, g_price_260, g_price_268, "My Buy Limit Position", 6789, 0, Blue);
}

void f0_4() {
   OrderSend(Symbol(), OP_SELLLIMIT, Lot, g_price_220, 3, g_price_276, g_price_284, "My Sell Limit Position", 9876, 0, Red);
}

int f0_0(string a_symbol_0, int a_magic_8, double ad_12) {
   int li_ret_20 = 0;
   for (int pos_24 = OrdersTotal() - 1; pos_24 >= 0; pos_24--) {
      if (OrderSelect(pos_24, SELECT_BY_POS) != FALSE) {
         if (OrderSymbol() == a_symbol_0) {
            if (OrderMagicNumber() == a_magic_8)
               if (NormalizeDouble(OrderOpenPrice(), Digits - 1) == ad_12) li_ret_20 += 1;
         }
      }
   }
   return (li_ret_20);
}

int f0_2(string a_symbol_0, int a_magic_8) {
   int li_ret_12 = 0;
   for (int pos_16 = OrdersTotal() - 1; pos_16 >= 0; pos_16--) {
      if (OrderSelect(pos_16, SELECT_BY_POS) != FALSE) {
         if (OrderSymbol() == a_symbol_0)
            if (OrderMagicNumber() == a_magic_8) li_ret_12 += 1;
      }
   }
   return (li_ret_12);
}

void f0_1() {
   Comment("\n\n\n                         FX Account Server = ", AccountServer(), 
      "\n", "                         Minimum Lot Sizing = ", MarketInfo(Symbol(), MODE_MINLOT), 
      "\n", "                         Maximum Lot Sizing = ", MarketInfo(Symbol(), MODE_MAXLOT), 
      "\n", "                         Pip StopLevel = ", MarketInfo(Symbol(), MODE_STOPLEVEL), 
      "\n", "                         Digits = ", MarketInfo(Symbol(), MODE_DIGITS), 
      "\n", "                         Account Name = ", AccountName(), 
      "\n", "                         Account Number = ", AccountNumber(), 
      "\n", "                         Account Company = ", AccountCompany(), 
      "\n", "                         Account Credit = ", AccountCredit(), 
      "\n", "                         Account Currency = ", AccountCurrency(), 
      "\n", "                         Account Balance =  $ ", AccountBalance(), 
      "\n", "                         Account Equity = $ ", AccountEquity(), 
      "\n", "                         Account Profit = ", AccountProfit(), 
      "\n", "                         Account Leverage = ", AccountLeverage(), 
      "\n", "                         Free margin = ", AccountFreeMargin(), 
      "\n", "                         Account Margin = ", AccountMargin(), 
      "\n", "                         Pip Spread =  ", MarketInfo(Symbol(), MODE_SPREAD), 
      "\n", "                         Symbol = ", Symbol(), 
   "\n", "                         Lots = ", Lot);
}